import type { Metadata } from "next"
import "./globals.css"
import ProviderLayout from "@/component/shared/providerLayout"

export const metadata: Metadata = {
  title: "얼루가게",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ProviderLayout>{children}</ProviderLayout>
      </body>
    </html>
  )
}
